import type { Metadata } from "next";
import { Inter } from "next/font/google";
import PartnersComponent from "@/shared/sections/partners/Partners.component";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Code & Care",
  description: "Generated by create next app",
};

export default function AboutUsLayout({
                                           children,
                                         }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      {children}
      <PartnersComponent />
    </>
  );
}
